### ISSUE TITLE
Support for 32  SIZE

### ISSUE THREAD

**Issue by RosGtHub** [polirritmico/Breeze-Dark-Cursor#1]
hi, i love this version of breeze! Can you make a 32 size version of it? I would really appreciate it and i think it could be useful also for others people.

**Comment by polirritmico** [comment]
Hi, I'm glad you like the theme; thanks for point it out.
I made this special release with 24, 32, 36, 48, 64 and 96 sizes:
https://github.com/polirritmico/Breeze-Dark-Cursor/releases/tag/extra-sizes_v0.1

However, since Breeze officially only supports 24, 36 and 48 cursors sizes I will not update the "main" version with this one until is properly tested or the official theme include those sizes.

Feel free to open a new issue if it has any trouble.

**Comment by RosGtHub** [comment]
Alright, thank you so much! [EDIT: It works perfectly. I literally love it!]
